### PR TITLE
New home page

### PR DESCRIPTION
**Pull request by ItsLuiggiYahoo**
Added:

- Image;
- Tutorial tab
- Reformulated some text
- Added a about tab

PS: Sorry for deleting the other one.

### CODE REVIEW

**Comment by StarManTheGamer** [comment]
image

Issue with the Flatpak format

image
Both links go to basic-scripting index. Both links are also a 404, and need to go to /tutorials/getting-started/

image

Image couldn't be found

Please make these changes before I can merge.
Please also use yarn to install prettier and run prettier to follow the format of the code.

**Review by StarManTheGamer — CHANGES_REQUESTED** [review]
^ Marking as changes requested

**Comment by ItsLuiggiYahoo** [comment]
That's strange it shouldn't be like that.

So it's pretty late here in my country, and I can't do the changes right now, I will fix them tomorrow between morning and evening. Thanks for pointing that out.

**Comment by indexxing** [comment]
What is [^1] supposed to do? [^1] is a footnote in MkDocs so you have to be careful with formatting.

**Comment by indexxing** [comment]
Oh wait never mind, just replace [^1] with (Built with Flatpack)

**Pull request merged**
